# Generated by Django 3.2.4 on 2021-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210620_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationsSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('mail', models.EmailField(blank=True, max_length=200, null=True)),
                ('Jour', models.DateTimeField(blank=True, null=True)),
                ('HeureDebut', models.TimeField(blank=True, null=True)),
                ('HeureFin', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
